/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 TiO2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import TiO2Url from '/models/TiO2.glb?url'

export function TiO2(props) {
  const { nodes, materials } = useGLTF(TiO2Url)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/TiO2.glb')

export default TiO2