/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lowpoly-flask.glb 
Author: BerserkerBroon (https://sketchfab.com/BerserkerBroon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-flask-dcf232cf9e964c478a1b2d59b8097510
Title: LowPoly - Flask
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Flask(props) {
  const { nodes, materials } = useGLTF('/models/lowpoly-flask.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Cork} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Liquid} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/lowpoly-flask.glb')
